---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Forceer Purge van Apache2 (voor een schone start)
  ansible.builtin.apt:
    name: apache2
    state: absent
    purge: yes
  become: yes

- name: Installeer Apache web server
  ansible.builtin.package:
    name: apache2
    state: present
    update_cache: yes
  become: yes
  notify: "herlaad_apache2"

- name: Zorg dat de Apache service start en ge-enabled is
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
  become: yes