name: terraform Deploy azure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/azure/*.tf'

jobs:
  terraform-deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./terraform/azure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: terraform init
        run: terraform init

      - name: terraform valideren
        run: terraform validate

      - name: terraform plan
        run: terraform plan

      - name: terraform apply
        run: terraform apply -auto-approve
